// Keeps src/version.ts in lockstep with package.json. Runs as part of the
// changesets `version` script so the User-Agent header always reports the
// version actually published.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pkg = JSON.parse(readFileSync(`${root}/package.json`, 'utf8'));

writeFileSync(
  `${root}/src/version.ts`,
  `// Auto-generated by scripts/sync-version.mjs — do not edit by hand.\nexport const VERSION = '${pkg.version}';\n`
);

console.log(`src/version.ts -> ${pkg.version}`);
